FROM python:3.12-slim

WORKDIR /srv/app
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/srv/app

COPY pyproject.toml ./
COPY app ./app
COPY alembic.ini ./
COPY .env.example ./
RUN pip install --no-cache-dir ".[postgres]"

EXPOSE 8000
CMD ["python", "-m", "app.main"]
