from __future__ import annotations


BASELINE_RESOURCE_DEFINITIONS = [
    {
        "key": "credits",
        "name": "Кредиты",
        "description": "Основная валюта станции.",
        "icon_key": "credits",
        "rarity": "common",
        "category": "currency",
        "base_price": 1.0,
        "sort_order": 1,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 1350,
    },
    {
        "key": "energy",
        "name": "Энергия",
        "description": "Питает модули и удерживает темп станции.",
        "icon_key": "energy",
        "rarity": "common",
        "category": "utility",
        "base_price": 10.0,
        "sort_order": 2,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 42,
    },
    {
        "key": "fuel",
        "name": "Топливо",
        "description": "Ключевой ресурс для логистики и контрактов.",
        "icon_key": "fuel",
        "rarity": "common",
        "category": "logistics",
        "base_price": 8.0,
        "sort_order": 3,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 48,
    },
    {
        "key": "parts",
        "name": "Детали",
        "description": "Расходник для апгрейдов и сервисных работ.",
        "icon_key": "parts",
        "rarity": "common",
        "category": "industry",
        "base_price": 13.0,
        "sort_order": 4,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 32,
    },
    {
        "key": "data",
        "name": "Данные",
        "description": "Цифровой поток для исследований и аналитики.",
        "icon_key": "data",
        "rarity": "uncommon",
        "category": "research",
        "base_price": 10.0,
        "sort_order": 5,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 22,
    },
    {
        "key": "crew",
        "name": "Экипаж",
        "description": "Люди, обеспечивающие работу станции.",
        "icon_key": "crew",
        "rarity": "uncommon",
        "category": "personnel",
        "base_price": 20.0,
        "sort_order": 6,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 5,
    },
    {
        "key": "alloy",
        "name": "Сплав",
        "description": "Конструкционный материал для тяжёлых модулей.",
        "icon_key": "alloy",
        "rarity": "uncommon",
        "category": "industry",
        "base_price": 15.0,
        "sort_order": 7,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 18,
    },
    {
        "key": "insight",
        "name": "Инсайт",
        "description": "Мета-ресурс для постоянных улучшений.",
        "icon_key": "insight",
        "rarity": "rare",
        "category": "meta",
        "base_price": 40.0,
        "sort_order": 8,
        "is_public": True,
        "is_visible": True,
        "enabled": True,
        "starting_amount": 5,
    },
    {
        "key": "reputation",
        "name": "Репутация",
        "description": "Доверие сектора к станции.",
        "icon_key": "reputation",
        "rarity": "meta",
        "category": "standing",
        "base_price": 0.0,
        "sort_order": 9,
        "is_public": False,
        "is_visible": False,
        "enabled": True,
        "starting_amount": 0,
    },
]


BASELINE_MODULE_DEFINITIONS = [
    {
        "key": "dock",
        "name": "Док",
        "description": "Расширяет входящий поток кораблей и повышает логистическую пропускную способность.",
        "category": "logistics",
        "max_level": 10,
        "base_cost": {"credits": 300, "parts": 20, "alloy": 10},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"ship_intake": 3, "contract_slots": 1},
        "effects": [{"type": "add_station_stat", "stat": "ship_intake", "value": 3}],
        "energy_delta": -2,
        "throughput_delta": 4,
        "crew_delta": 0,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": ["freight_hub"],
        "sort_order": 10,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "warehouse",
        "name": "Склад",
        "description": "Даёт безопасное хранение и снижает штрафы от переполнения.",
        "category": "storage",
        "max_level": 10,
        "base_cost": {"credits": 250, "parts": 15, "alloy": 12},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"storage": 100},
        "effects": [{"type": "add_storage_capacity", "value": 100}],
        "energy_delta": -1,
        "throughput_delta": 3,
        "crew_delta": 0,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": [],
        "sort_order": 20,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "reactor",
        "name": "Реактор",
        "description": "Даёт запас энергии для новых модулей и роста станции.",
        "category": "power",
        "max_level": 10,
        "base_cost": {"credits": 300, "parts": 16, "alloy": 18},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"energy_supply": 15},
        "effects": [{"type": "add_energy_generation", "value": 15}],
        "energy_delta": 15,
        "throughput_delta": 2,
        "crew_delta": 0,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": [],
        "sort_order": 30,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "repair_bay",
        "name": "Ремонтный отсек",
        "description": "Открывает сервисные заказы и повышает доход от ремонта.",
        "category": "service",
        "max_level": 10,
        "base_cost": {"credits": 260, "parts": 22, "alloy": 14},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"repair_capacity": 8},
        "effects": [{"type": "add_station_stat", "stat": "repair_capacity", "value": 8}],
        "energy_delta": -3,
        "throughput_delta": 5,
        "crew_delta": -1,
        "crew_requirement": 1,
        "unlock_requirements": [],
        "specialization_tags": ["repair_nexus"],
        "sort_order": 40,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "habitat",
        "name": "Жилой модуль",
        "description": "Стабилизирует экипаж и повышает потолок нагрузки станции.",
        "category": "crew",
        "max_level": 10,
        "base_cost": {"credits": 180, "parts": 8, "alloy": 8},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"crew_capacity": 4, "stability": 3},
        "effects": [{"type": "add_station_stat", "stat": "crew_capacity", "value": 4}],
        "energy_delta": -2,
        "throughput_delta": 1,
        "crew_delta": 2,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": [],
        "sort_order": 50,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "market_terminal",
        "name": "Рыночный терминал",
        "description": "Улучшает маржу сделок и открывает больше NPC-контрактов.",
        "category": "trade",
        "max_level": 10,
        "base_cost": {"credits": 220, "parts": 10, "data": 8},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"trade_bonus": 0.08},
        "effects": [{"type": "add_market_bonus", "value": 0.08}],
        "energy_delta": -1,
        "throughput_delta": 5,
        "crew_delta": 0,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": ["freight_hub", "data_exchange"],
        "sort_order": 60,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "data_core",
        "name": "Дата-ядро",
        "description": "Разгоняет поток данных, инсайта и аналитических заказов.",
        "category": "research",
        "max_level": 10,
        "base_cost": {"credits": 250, "parts": 12, "data": 18},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"data_output": 8, "insight_gain": 1.1},
        "effects": [{"type": "add_resource_production", "resource": "data", "value": 8}],
        "energy_delta": -2,
        "throughput_delta": 4,
        "crew_delta": 0,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": ["data_exchange"],
        "sort_order": 70,
        "enabled": True,
        "is_visible": True,
    },
    {
        "key": "automation_hub",
        "name": "Узел автоматизации",
        "description": "Поздний усилитель всей станции: дорогой, но отлично масштабируется.",
        "category": "automation",
        "max_level": 10,
        "base_cost": {"credits": 420, "parts": 24, "data": 16, "alloy": 16},
        "upgrade_cost_growth": 0.45,
        "base_effect": {"automation": 0.1},
        "effects": [{"type": "add_station_stat", "stat": "automation", "value": 0.1}],
        "energy_delta": -3,
        "throughput_delta": 7,
        "crew_delta": 0,
        "crew_requirement": 0,
        "unlock_requirements": [],
        "specialization_tags": [],
        "sort_order": 80,
        "enabled": True,
        "is_visible": True,
    },
]


BASELINE_EVENT_DEFINITIONS = [
    {
        "key": "fuel_surge",
        "title": "Всплеск спроса на топливо",
        "short_description": "Сектору срочно нужно больше топлива.",
        "long_description": "Торговые линии резко подняли потребление топлива, и рынок реагирует ростом цен.",
        "event_type": "market_shift",
        "duration_minutes": 60,
        "weight": 1.0,
        "conditions": {"all": [{"field": "sector_player_count", "op": ">=", "value": 1}]},
        "market_effects": {"fuel": 1.18},
        "effects": [{"type": "apply_sector_modifier", "target": "fuel", "value": 1.18}],
        "scope": "sector",
        "enabled": True,
        "cooldown_minutes": 30,
        "tags": ["market", "fuel"],
    },
    {
        "key": "parts_shortage",
        "title": "Дефицит деталей",
        "short_description": "Сервисные узлы съедают запасы деталей.",
        "long_description": "Ремонтные доки сектора резко подняли потребление деталей, что ускорило рост цены.",
        "event_type": "market_shift",
        "duration_minutes": 60,
        "weight": 0.9,
        "conditions": {"all": [{"field": "sector_player_count", "op": ">=", "value": 1}]},
        "market_effects": {"parts": 1.15},
        "effects": [{"type": "apply_sector_modifier", "target": "parts", "value": 1.15}],
        "scope": "sector",
        "enabled": True,
        "cooldown_minutes": 30,
        "tags": ["market", "parts"],
    },
    {
        "key": "scientific_grant",
        "title": "Научный грант",
        "short_description": "Данные и аналитика временно дорожают.",
        "long_description": "Фонды сектора выдают новые гранты, подогревая спрос на данные и исследования.",
        "event_type": "reward_boost",
        "duration_minutes": 60,
        "weight": 0.8,
        "conditions": {"all": [{"field": "sector_player_count", "op": ">=", "value": 1}]},
        "market_effects": {"data": 1.12},
        "effects": [{"type": "apply_sector_modifier", "target": "data", "value": 1.12}],
        "scope": "sector",
        "enabled": True,
        "cooldown_minutes": 45,
        "tags": ["research"],
    },
]


BASELINE_CONTRACT_TEMPLATES = [
    {"key": "fuel_shuttle", "title": "Топливный шаттл", "contract_type": "delivery", "resource": "fuel", "quantity": 18, "reward_credits": 210, "reward_reputation": 1, "enabled": True, "tags": ["starter"]},
    {"key": "alloy_batch", "title": "Партия сплава", "contract_type": "delivery", "resource": "alloy", "quantity": 14, "reward_credits": 235, "reward_reputation": 1, "enabled": True, "tags": []},
    {"key": "parts_repair", "title": "Латка корпуса", "contract_type": "repair", "resource": "parts", "quantity": 16, "reward_credits": 250, "reward_reputation": 2, "enabled": True, "tags": ["repair"]},
    {"key": "data_dump", "title": "Выгрузка телеметрии", "contract_type": "data", "resource": "data", "quantity": 14, "reward_credits": 225, "reward_reputation": 1, "enabled": True, "tags": ["data"]},
]


BASELINE_META_UPGRADES = [
    {"key": "boot_efficiency", "name": "Эффективный запуск", "description": "+5% к пропускной способности", "base_cost": 5, "max_level": 3, "effect_type": "throughput_pct", "effect_value": 0.05, "enabled": True},
    {"key": "market_acuity", "name": "Рыночная точность", "description": "+4% к торговой марже", "base_cost": 6, "max_level": 3, "effect_type": "trade_margin_pct", "effect_value": 0.04, "enabled": True},
    {"key": "crew_protocols", "name": "Протоколы экипажа", "description": "+1 к базовому персоналу", "base_cost": 4, "max_level": 4, "effect_type": "crew_flat", "effect_value": 1.0, "enabled": True},
]


BASELINE_SPECIALIZATIONS = [
    {
        "key": "freight_hub",
        "name": "Фрахтовый узел",
        "description": "Станция, заточенная под логистику и топливо.",
        "throughput_multiplier": 1.12,
        "focus_resource": "fuel",
        "sort_order": 1,
        "enabled": True,
    },
    {
        "key": "repair_nexus",
        "name": "Ремонтный узел",
        "description": "Сильнее раскрывает сервис и ремонт.",
        "throughput_multiplier": 1.12,
        "focus_resource": "parts",
        "sort_order": 2,
        "enabled": True,
    },
    {
        "key": "data_exchange",
        "name": "Биржа данных",
        "description": "Делает ставку на аналитику и инсайт.",
        "throughput_multiplier": 1.12,
        "focus_resource": "data",
        "sort_order": 3,
        "enabled": True,
    },
]


BASELINE_BALANCE_PARAMETERS = [
    {"key": "market_trade_bonus_per_level", "category": "market", "scope": "global", "value": {"value": 0.03}},
    {"key": "market_buy_discount_floor", "category": "market", "scope": "global", "value": {"value": 0.72}},
    {"key": "market_min_buy_multiplier", "category": "market", "scope": "global", "value": {"value": 0.92}},
    {"key": "market_sell_bonus_ratio", "category": "market", "scope": "global", "value": {"value": 0.6}},
    {"key": "market_sell_spread", "category": "market", "scope": "global", "value": {"value": 0.18}},
    {"key": "market_max_sell_multiplier", "category": "market", "scope": "global", "value": {"value": 0.88}},
    {"key": "market_mean_reversion_per_minute", "category": "market", "scope": "global", "value": {"value": 0.25}},
    {"key": "market_price_floor_multiplier", "category": "market", "scope": "global", "value": {"value": 0.35}},
    {"key": "market_price_cap_multiplier", "category": "market", "scope": "global", "value": {"value": 6.0}},
    {"key": "market_event_multiplier_cap", "category": "market", "scope": "global", "value": {"value": 3.0}},
    {"key": "world_event_spawn_chance", "category": "events", "scope": "global", "value": {"value": 0.35}},
    {"key": "market_price_drift_min", "category": "market", "scope": "global", "value": {"value": -0.04}},
    {"key": "market_price_drift_max", "category": "market", "scope": "global", "value": {"value": 0.04}},
    {"key": "npc_contract_target_open", "category": "contracts", "scope": "global", "value": {"value": 8}},
    {"key": "report_interval_seconds", "category": "simulation", "scope": "global", "value": {"value": 60}},
]
